# Generated by Django 2.1.5 on 2019-01-30 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Guest',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='user_id',
            new_name='guest_id',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='username',
            new_name='guestname',
        ),
    ]
