# Generated by Django 2.1.5 on 2019-01-31 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190130_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleGuest',
            fields=[
                ('simple_guest_name', models.CharField(max_length=200)),
                ('simple_guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('simple_guest_created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
